### ISSUE TITLE
Use pytest / Codecov

### ISSUE THREAD

**Issue by madhavtummala** [dsciitbbs/piesAndBars#2]
For testing flask applications, it would be ideal to use pytest.
Without that the coverage reports would not account for much.

[Testing](http://flask.pocoo.org/docs/1.0/testing/)
[Tutorials](http://flask.pocoo.org/docs/1.0/tutorial/tests/)

**Comment by PalAditya** [comment]
Noted and added initial tests, although more is definitely welcome.

**Comment by PalAditya** [comment]
Resolved in 345d3081e44fa84947b9b335e4cc582db8188af1
